package com.nashvi.labs.model;

// Generated May 4, 2014 8:19:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address")
public class Address implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private AddressId id;
	private Users users;

	public Address() {
	}

	public Address(AddressId id, Users users) {
		this.id = id;
		this.users = users;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 15)),
			@AttributeOverride(name = "street", column = @Column(name = "street", nullable = false, length = 45)),
			@AttributeOverride(name = "city", column = @Column(name = "city", nullable = false, length = 45)),
			@AttributeOverride(name = "country", column = @Column(name = "country", nullable = false, length = 45)),
			@AttributeOverride(name = "zip", column = @Column(name = "zip", nullable = false)),
			@AttributeOverride(name = "phone", column = @Column(name = "phone")),
			@AttributeOverride(name = "email", column = @Column(name = "email", length = 45)) })
	public AddressId getId() {
		return this.id;
	}

	public void setId(AddressId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
