package com.nashvi.labs.model;

// Generated May 4, 2014 8:19:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
//@Entity
@Table(name = "users")
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String userId;
	private String password;
	private Date createTimestamp;
	private Date lastLoginTimestamp;
	private int invalidLoginAttempt;
	private char status;
	private String roles;
	private Set<Address> addresses = new HashSet<Address>(0);

	public Users() {
	}

	public Users(String userId, String password, Date createTimestamp,
			Date lastLoginTimestamp, int invalidLoginAttempt, char status) {
		this.userId = userId;
		this.password = password;
		this.createTimestamp = createTimestamp;
		this.lastLoginTimestamp = lastLoginTimestamp;
		this.invalidLoginAttempt = invalidLoginAttempt;
		this.status = status;
	}

	public Users(String userId, String password, Date createTimestamp,
			Date lastLoginTimestamp, int invalidLoginAttempt, char status,
			String roles, Set<Address> addresses) {
		this.userId = userId;
		this.password = password;
		this.createTimestamp = createTimestamp;
		this.lastLoginTimestamp = lastLoginTimestamp;
		this.invalidLoginAttempt = invalidLoginAttempt;
		this.status = status;
		this.roles = roles;
		this.addresses = addresses;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false, length = 15)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "password", nullable = false, length = 15)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_timestamp", nullable = false, length = 19)
	public Date getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(Date createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_login_timestamp", nullable = false, length = 19)
	public Date getLastLoginTimestamp() {
		return this.lastLoginTimestamp;
	}

	public void setLastLoginTimestamp(Date lastLoginTimestamp) {
		this.lastLoginTimestamp = lastLoginTimestamp;
	}

	@Column(name = "invalid_login_attempt", nullable = false)
	public int getInvalidLoginAttempt() {
		return this.invalidLoginAttempt;
	}

	public void setInvalidLoginAttempt(int invalidLoginAttempt) {
		this.invalidLoginAttempt = invalidLoginAttempt;
	}

	@Column(name = "status", nullable = false, length = 1)
	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	@Column(name = "roles", length = 45)
	public String getRoles() {
		return this.roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
